name: Trigger GitHub pages rebuild every day at 1:00am

on:
    workflow_dispatch:
    schedule:
    - cron: '0 1 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
          curl --fail --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
          --header "Authorization: Bearer $USER_TOKEN"
      env:
          # Settings > Developer settings > Personal access tokens > Generate new token > repo scope
          USER_TOKEN: ${{ secrets.PAGES_ACCESS_TOKEN }}
